language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

before_script:
  - 'composer install --dev --prefer-source'

script: php test/test.php
